version: '3'

services:
  api:
    build: ./api
    command: python ./api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/volume
    ports:
      - "80:80"
    environment:
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_URL=${SUPABASE_URL}

  website:
    build: ./webapp
    ports:
      - "3000:3000"
