import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import Link from 'next/link';
import Image from "next/image";
import logo from '@/app/logo.png'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export const TopBar = () => {
    return (
        <div className="topbar">
            <div className="left">
                <Image src={logo} width={35} height={35} alt="logo" className="logo" />
                <span className="appname">PriceProbe</span>
            </div>
            <div className="right">
                <Link href="/home">Home</Link>
            </div>
        </div>
    )
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><TopBar />{children}</body>
    </html>
  )
}
